#![allow(dead_code)]

use chrono::{DateTime, Utc};
use uuid::Uuid;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ReportType {
    Executive,
    Technical,
    Combined,
    FindingsOnly,
    EvidencePackage,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OutputFormat {
    Html,
    Markdown,
    Pdf,
    Json,
}

#[derive(Debug, Clone)]
pub struct ReportConfig {
    pub report_type: ReportType,
    pub output_format: OutputFormat,
    pub assessment_id: Uuid,
    pub include_evidence: bool,
    pub include_charts: bool,
    pub branding: Branding,
}

#[derive(Debug, Clone)]
pub struct Branding {
    pub company_name: String,
    pub company_logo: Option<String>,
    pub consultant_name: String,
    pub footer_text: String,
    pub primary_color: String,
}

impl Default for Branding {
    fn default() -> Self {
        Self {
            company_name: "Sentinel Security".into(),
            company_logo: None,
            consultant_name: String::new(),
            footer_text: "Generated by Sentinel".into(),
            primary_color: "#2563eb".into(),
        }
    }
}

#[derive(Debug, Clone)]
pub struct FindingSummary {
    pub title: String,
    pub severity: String,
    pub confidence: String,
    pub description: String,
    pub impact: String,
    pub recommendation: String,
    pub evidence: Vec<String>,
    pub references: String,
    pub cwe: Option<String>,
    pub owasp_category: Option<String>,
}

#[derive(Debug, Clone)]
pub struct ReportData {
    pub assessment_name: String,
    pub assessment_target: String,
    pub scope: String,
    pub duration: String,
    pub total_findings: usize,
    pub findings: Vec<FindingSummary>,
    pub severity_counts: SeverityCounts,
    pub generated_at: DateTime<Utc>,
}

#[derive(Debug, Clone, Default)]
pub struct SeverityCounts {
    pub critical: usize,
    pub high: usize,
    pub medium: usize,
    pub low: usize,
    pub informational: usize,
}
