use crate::models::knowledge::KnowledgeEntry;

const WSTG_JSON: &str = include_str!("wstg_knowledge.json");

pub fn load_all() -> Vec<KnowledgeEntry> {
    let mut entries: Vec<KnowledgeEntry> = serde_json::from_str(WSTG_JSON).unwrap_or_default();
    entries.extend(load_jwt_knowledge());
    entries
}

pub fn load_jwt_knowledge() -> Vec<KnowledgeEntry> {
    vec![
        KnowledgeEntry {
            reference: "WSTG-ATHN-04".to_string(),
            title: "JWT Security Testing".to_string(),
            objective: "Identify JSON Web Token (JWT) implementation weaknesses including algorithm confusion, missing expiration, sensitive data exposure, and weak signing algorithms.".to_string(),
            description: "JSON Web Tokens (JWTs) are widely used for authentication and authorization in modern web applications. Testing JWT implementations involves examining the token structure, algorithm selection, claim validation, and signature verification. Common vulnerabilities include accepting tokens signed with the 'none' algorithm, using weak HMAC or RSA keys, missing expiration claims, and exposing sensitive information in token claims.".to_string(),
            prerequisites: "Access to application authentication flow, ability to capture HTTP traffic, understanding of JWT structure (header.payload.signature).".to_string(),
            testing_steps: "1. Capture JWT tokens from Authorization headers, cookies, or response bodies.\n2. Decode base64url-encoded header and payload sections.\n3. Analyze the algorithm (alg) field in the header.\n4. Check if 'none' algorithm is accepted.\n5. Verify all standard claims (exp, nbf, iat, iss, sub, aud) are properly validated.\n6. Test for algorithm confusion (e.g., changing RS256 to HS256).\n7. Check for sensitive data in claims.\n8. Test token expiration behavior.".to_string(),
            expected_result: "The application should:\n- Reject tokens with 'none' algorithm.\n- Properly validate 'exp', 'nbf', and 'iat' claims.\n- Use strong asymmetric algorithms (RS256+, ES256+).\n- Not expose sensitive data in JWT claims.\n- Enforce proper key management with 'kid' header.".to_string(),
            required_evidence: "Decoded JWT tokens, proof of token acceptance/rejection, server responses showing validation behavior, key material evidence.".to_string(),
            references: "OWASP ASVS V3.1.1\nCWE-345: Insufficient Verification of Data Authenticity\nCWE-327: Use of a Broken or Risky Cryptographic Algorithm\nCWE-613: Insufficient Session Expiration\nRFC 7519: JSON Web Token (JWT)\nOWASP API Security Top 10 - API2:2023 Broken Authentication".to_string(),
        },
        KnowledgeEntry {
            reference: "WSTG-ATHN-04-ALG".to_string(),
            title: "JWT Algorithm Confusion Attack".to_string(),
            objective: "Test if the JWT implementation is vulnerable to algorithm confusion attacks, where an attacker can switch between asymmetric and symmetric signing algorithms.".to_string(),
            description: "Algorithm confusion attacks occur when a server uses an asymmetric algorithm (e.g., RS256) to verify tokens but does not properly restrict the accepted algorithms. An attacker can change the algorithm to a symmetric one (e.g., HS256) and sign the token with the server's public key (which is treated as the HMAC secret). The server, lacking proper key-type validation, will verify the forged token.".to_string(),
            prerequisites: "Access to JWT tokens, knowledge of the server's public key (if RSA is used), ability to forge and replay tokens.".to_string(),
            testing_steps: "1. Capture a valid JWT signed with an asymmetric algorithm (RS256/ES256).\n2. Decode the token and examine the header.\n3. Change the 'alg' to 'HS256'.\n4. Use the server's public key as the HMAC secret to re-sign the token.\n5. Submit the modified token to the server.\n6. Observe if the server accepts the token.".to_string(),
            expected_result: "The server should reject tokens where the algorithm type (symmetric vs. asymmetric) does not match the expected key type for that application. Proper implementations validate both the algorithm and key type.".to_string(),
            required_evidence: "Original JWT token, modified token, server response showing acceptance or rejection, server public key.".to_string(),
            references: "CWE-345: Insufficient Verification of Data Authenticity\nOWASP ASVS V3.1.3\nRFC 7518: JSON Web Algorithms (JWA)\nBlack Hat 2016: JWT Attack Walkthrough".to_string(),
        },
        KnowledgeEntry {
            reference: "WSTG-ATHN-04-NONE".to_string(),
            title: "JWT None Algorithm Attack".to_string(),
            objective: "Test if the server accepts JWT tokens signed with the 'none' algorithm, effectively bypassing all signature verification.".to_string(),
            description: "The 'none' algorithm was originally included in the JWT specification for cases where integrity is already guaranteed by other means. However, many JWT libraries have historically accepted 'none' algorithm tokens without proper configuration. If a server accepts 'none' algorithm tokens, an attacker can forge any claims they want.".to_string(),
            prerequisites: "Access to application endpoints that accept JWT tokens, ability to construct and submit HTTP requests.".to_string(),
            testing_steps: "1. Capture a valid JWT from the application.\n2. Decode the token and extract the payload.\n3. Construct a new JWT with header alg=none.\n4. Modify the payload claims as desired (e.g., escalate privileges).\n5. Submit the token with an empty signature.\n6. Observe if the server accepts and processes the token.".to_string(),
            expected_result: "The server should reject any JWT with 'alg': 'none'. JWT libraries must be configured to explicitly disallow the none algorithm in production.".to_string(),
            required_evidence: "Modified JWT with 'alg': 'none', server response, proof of elevated access or accepted claims.".to_string(),
            references: "CWE-345: Insufficient Verification of Data Authenticity\nOWASP ASVS V3.1.1\nRFC 7519 Section 6.1\nOWASP API Security Top 10 - API2:2023".to_string(),
        },
        KnowledgeEntry {
            reference: "WSTG-ATHN-04-EXP".to_string(),
            title: "JWT Expiration and Session Management".to_string(),
            objective: "Verify that JWT expiration is properly enforced and that token lifetimes follow security best practices.".to_string(),
            description: "JWTs that never expire (missing 'exp' claim) or have excessively long lifetimes pose a significant security risk. If a token is stolen, the attacker has unlimited time to use it. Access tokens should have short lifetimes (15-60 minutes), while refresh tokens can have longer lifetimes with additional protections.".to_string(),
            prerequisites: "Access to JWT tokens, ability to replay tokens at different times.".to_string(),
            testing_steps: "1. Decode the JWT and check for the 'exp' claim.\n2. Calculate the token lifetime (exp - iat).\n3. Wait for the token to expire and attempt to reuse it.\n4. If no 'exp' is present, note the token accepts indefinitely.\n5. Check for proper clock skew handling (typically 30-60 seconds).".to_string(),
            expected_result: "Tokens should:\n- Always include an 'exp' claim.\n- Have a reasonable lifetime (15-60 minutes for access tokens).\n- Be rejected after expiration.\n- Handle clock skew gracefully without extending token validity excessively.".to_string(),
            required_evidence: "Token lifetime calculation, server responses for expired tokens, configuration documentation.".to_string(),
            references: "CWE-613: Insufficient Session Expiration\nOWASP ASVS V3.3.2\nRFC 7519 Section 4.1.4\nNIST SP 800-63B Section 7.1".to_string(),
        },
        KnowledgeEntry {
            reference: "WSTG-ATHN-04-DATA".to_string(),
            title: "JWT Sensitive Data Exposure".to_string(),
            objective: "Identify sensitive information exposed in JWT claims that should not be included in signed (but not encrypted) tokens.".to_string(),
            description: "JWTs are base64url-encoded, not encrypted. Anyone who captures a JWT can easily decode and read all claims. Storing sensitive data such as passwords, API keys, personal information (PII), or internal identifiers in JWT claims exposes this data to anyone who intercepts the token. This is a common anti-pattern in JWT implementations.".to_string(),
            prerequisites: "Access to captured JWT tokens, understanding of what constitutes sensitive data for the application.".to_string(),
            testing_steps: "1. Capture JWT tokens from the application.\n2. Decode the base64url payload section.\n3. Review all claims for sensitive data patterns:\n   - Personal identifiers (email, phone, SSN).\n   - Authorization details (roles, permissions).\n   - Internal resource IDs.\n   - Session or API keys.\n   - Debug or configuration data.\n4. Assess if any identified data should be server-side only.".to_string(),
            expected_result: "JWT claims should contain only the minimum necessary information for stateless authentication. Sensitive data should be stored server-side and referenced by an opaque identifier.".to_string(),
            required_evidence: "Decoded JWT payload, identified sensitive claims, justification for why claims are sensitive.".to_string(),
            references: "CWE-312: Cleartext Storage of Sensitive Information\nOWASP ASVS V3.1.4\nRFC 7519 Section 4\nOWASP API Security Top 10 - API3:2023".to_string(),
        },
        KnowledgeEntry {
            reference: "WSTG-ATHN-04-WEAK".to_string(),
            title: "JWT Weak Signing Algorithms".to_string(),
            objective: "Identify JWT implementations using cryptographically weak or deprecated signing algorithms.".to_string(),
            description: "The JWT specification supports multiple signing algorithms with varying security properties. HS256 uses HMAC with SHA-256, which can be susceptible to brute-force attacks with weak secrets. RS256 is vulnerable if key sizes are too small. ES256 is generally considered strong. The choice of algorithm and key strength directly impacts the security of the token.".to_string(),
            prerequisites: "Access to JWT tokens, understanding of cryptographic algorithm strengths.".to_string(),
            testing_steps: "1. Decode the JWT header and extract the 'alg' field.\n2. Identify if the algorithm is considered weak (HS256, RS256 with small keys).\n3. For HMAC-based tokens, test if short or common secrets are used.\n4. Check if the server accepts downgraded algorithms.\n5. Verify key lengths meet current standards (>=2048-bit RSA, >=256-bit EC).".to_string(),
            expected_result: "Applications should use strong algorithms with adequate key sizes:\n- Asymmetric: RS256+ (2048+ bit), ES256+ (P-256+).\n- Symmetric: HS256+ with at least 256-bit random secrets.\n- 'none' algorithm must be explicitly rejected.".to_string(),
            required_evidence: "JWT algorithm details, key size evidence, proof of algorithm downgrade acceptance, server configuration.".to_string(),
            references: "CWE-327: Use of a Broken or Risky Cryptographic Algorithm\nOWASP ASVS V3.5.1\nRFC 7518: JSON Web Algorithms\nNIST SP 800-57 Part 1".to_string(),
        },
        KnowledgeEntry {
            reference: "WSTG-ATHN-05".to_string(),
            title: "OAuth 2.0 Implementation Testing".to_string(),
            objective: "Identify security weaknesses in OAuth 2.0 implementations including missing PKCE, insecure redirect URIs, legacy flow usage, missing CSRF protection, and token handling vulnerabilities.".to_string(),
            description: "OAuth 2.0 is the industry standard for delegated authorization. Common implementation flaws include: not implementing PKCE for public clients, allowing wildcard redirect URIs, accepting tokens with overly broad scopes, exposing client secrets in frontend code, and failing to validate the state parameter against CSRF attacks. Testing OAuth requires analyzing the complete authorization flow from request to token exchange.".to_string(),
            prerequisites: "Access to OAuth-protected application, ability to intercept HTTP traffic, understanding of OAuth 2.0 flows and terminology (RFC 6749, RFC 7636).".to_string(),
            testing_steps: "1. Identify OAuth authorization and token endpoints from traffic.\n2. Check if PKCE (Proof Key for Code Exchange) is implemented for authorization code flows.\n3. Verify the redirect URI is exact-match and uses HTTPS.\n4. Check if state parameter is present and cryptographically random.\n5. Analyze requested scopes for excessive permissions.\n6. Inspect access and refresh token lifetimes.\n7. Test for authorization code reuse.\n8. Verify token endpoint authentication method.\n9. Check for OIDC nonce parameter in authorization requests.".to_string(),
            expected_result: "OAuth implementations should:\n- Use PKCE with S256 for all authorization code flows.\n- Enforce exact-match HTTPS redirect URIs.\n- Include cryptographically random state parameters.\n- Use minimal scopes (principle of least privilege).\n- Set short-lived access tokens (<= 1 hour).\n- Authenticate clients at the token endpoint.\n- Rotate refresh tokens on use.".to_string(),
            required_evidence: "Captured OAuth traffic, decoded tokens, redirect URI configuration, scope definitions, token response parameters.".to_string(),
            references: "OWASP ASVS V3.1.1\nCWE-384: Session Fixation\nCWE-601: URL Redirection to Untrusted Site\nRFC 6749: OAuth 2.0 Authorization Framework\nRFC 7636: Proof Key for Code Exchange (PKCE)\nOWASP API Security Top 10 - API2:2023 Broken Authentication".to_string(),
        },
        KnowledgeEntry {
            reference: "WSTG-ATHN-05-PKCE".to_string(),
            title: "OAuth PKCE Implementation Analysis".to_string(),
            objective: "Verify that PKCE (Proof Key for Code Exchange) is properly implemented to prevent authorization code interception attacks in OAuth 2.0 flows.".to_string(),
            description: "PKCE (RFC 7636) adds an additional layer of security to the authorization code flow by cryptographically binding the authorization request to the token request. The client generates a code_verifier (random string), derives a code_challenge from it (using S256 hashing), and sends only the challenge in the authorization request. The token endpoint then requires the original verifier to exchange the authorization code for tokens. This prevents attackers who intercept authorization codes from obtaining tokens without the verifier.".to_string(),
            prerequisites: "Access to OAuth authorization flow, ability to intercept HTTP requests and responses, understanding of PKCE protocol (RFC 7636).".to_string(),
            testing_steps: "1. Initiate an OAuth authorization code flow.\n2. Check if code_challenge and code_challenge_method parameters are present in the authorization request.\n3. Verify code_challenge_method is 'S256' (not 'plain').\n4. Check that the authorization server enforces PKCE - attempt token exchange without code_verifier.\n5. Test with an incorrect code_verifier to verify server validation.\n6. Verify code_verifier length is between 43-128 characters.".to_string(),
            expected_result: "PKCE implementations should:\n- Always use S256 code challenge method (never 'plain').\n- Reject token exchanges without valid code_verifier.\n- Reject token exchanges with incorrect code_verifier.\n- Enforce code_verifier length requirements (43-128 chars).\n- Use only allowed characters (A-Z, a-z, 0-9, -, ., _, ~).".to_string(),
            required_evidence: "Authorization request showing code_challenge, token request showing code_verifier, server responses validating PKCE enforcement, URL-encoded parameters from captured traffic.".to_string(),
            references: "RFC 7636: Proof Key for Code Exchange\nOWASP ASVS V3.3.1\nCWE-384: Session Fixation\nOAuth 2.1 Draft (mandates PKCE)".to_string(),
        },
        KnowledgeEntry {
            reference: "WSTG-ATHN-05-REDIR".to_string(),
            title: "OAuth Redirect URI Validation".to_string(),
            objective: "Test the OAuth authorization server's redirect URI validation to prevent authorization code interception through redirect manipulation attacks.".to_string(),
            description: "The authorization server must strictly validate redirect URIs against a pre-registered allowlist. Weak validation allows attackers to redirect authorization codes to their own servers. Common vulnerabilities include: accepting wildcard patterns, allowing HTTP (non-HTTPS) URIs, accepting localhost URIs, allowing open redirects on the client domain, and not validating the entire redirect URI path.".to_string(),
            prerequisites: "Access to OAuth authorization endpoint, registered client application, understanding of redirect URI validation in OAuth.".to_string(),
            testing_steps: "1. Register or identify a valid redirect URI for the client.\n2. Attempt authorization with a modified redirect URI (e.g., different domain).\n3. Test wildcard patterns in redirect URI.\n4. Change HTTPS to HTTP in the redirect URI.\n5. Add path traversal to redirect URI.\n6. Try open redirect on the registered domain.\n7. Test with additional query parameters appended to redirect URI.\n8. Attempt cross-origin redirect URIs.".to_string(),
            expected_result: "Authorization server should:\n- Reject redirect URIs that don't exactly match the registered URI.\n- Require HTTPS for all redirect URIs.\n- Not accept wildcard patterns.\n- Validate the full URI including path and query.\n- Not follow open redirects on registered domains.".to_string(),
            required_evidence: "Redirect URI modification attempts, server responses showing rejection or acceptance of invalid URIs, registered client configuration evidence.".to_string(),
            references: "OWASP ASVS V3.2.2\nCWE-601: URL Redirection to Untrusted Site\nRFC 6749 Section 3.1.2\nOAuth 2.0 Security Best Current Practice (BCP)".to_string(),
        },
        KnowledgeEntry {
            reference: "WSTG-ATHN-05-SCOPE".to_string(),
            title: "OAuth Scope Analysis and Privilege Escalation".to_string(),
            objective: "Identify excessive OAuth scopes and test for privilege escalation through scope manipulation during the authorization flow.".to_string(),
            description: "OAuth scopes define the permissions granted to a client application. Applications often request more scopes than needed, violating the principle of least privilege. More critically, some implementations allow clients to request additional or administrative scopes that are not authorized, leading to privilege escalation. Testing involves analyzing requested scopes and attempting to add or modify scopes during the authorization flow.".to_string(),
            prerequisites: "Access to OAuth authorization flow, legitimate client credentials, understanding of the application's scope definitions.".to_string(),
            testing_steps: "1. Analyze all scopes requested during the authorization flow.\n2. Determine if each scope is necessary for the application's functionality.\n3. Attempt to add additional scopes (e.g., 'admin', 'write', '*') to the authorization request.\n4. Try scope escalation during token refresh.\n5. Check if resource server properly validates token scopes.\n6. Test with scopes from other clients or services.".to_string(),
            expected_result: "OAuth implementations should:\n- Only request scopes strictly necessary for functionality.\n- Reject authorization requests with unauthorized additional scopes.\n- Validate scopes on the resource server for each API call.\n- Not allow scope escalation during token refresh.\n- Implement scope-to-role mapping on the server side.".to_string(),
            required_evidence: "List of requested scopes, results of scope modification attempts, resource server responses to modified scopes, client configuration showing authorized scopes.".to_string(),
            references: "OWASP ASVS V4.1.1\nCWE-285: Improper Authorization\nRFC 6749 Section 3.3\nOWASP API Security Top 10 - API1:2023 Broken Object Level Authorization".to_string(),
        },
        KnowledgeEntry {
            reference: "WSTG-ATHN-05-OIDC".to_string(),
            title: "OpenID Connect Security Testing".to_string(),
            objective: "Verify the security of OpenID Connect implementations through discovery document analysis, ID token validation, and claims verification.".to_string(),
            description: "OpenID Connect adds an identity layer on top of OAuth 2.0. The OIDC discovery document (.well-known/openid-configuration) exposes provider configuration including endpoints, supported algorithms, and claims. Testing involves analyzing this metadata, verifying ID token contents and signatures, validating claims, and checking for proper session management including logout.".to_string(),
            prerequisites: "Access to OIDC provider, captured ID tokens, understanding of OIDC specification and JWT validation.".to_string(),
            testing_steps: "1. Retrieve and analyze the OIDC discovery document.\n2. Verify supported algorithms are strong (RS256+, ES256+).\n3. Check if 'none' algorithm is rejected.\n4. Validate ID token signature.\n5. Verify ID token claims (iss, sub, aud, exp, iat).\n6. Check if nonce claim matches the request.\n7. Test session management (RP-initiated logout).\n8. Verify token revocation functionality.".to_string(),
            expected_result: "OIDC implementations should:\n- Provide discovery document at /.well-known/openid-configuration.\n- Support only strong signing algorithms.\n- Properly sign and validate ID tokens.\n- Include and validate nonce in authorization flow.\n- Support proper session termination.\n- Implement token revocation endpoints.".to_string(),
            required_evidence: "OIDC discovery document, decoded ID tokens, authorization and token request parameters, session termination evidence.".to_string(),
            references: "OpenID Connect Core 1.0\nOWASP ASVS V3.3.1\nCWE-345: Insufficient Verification\nRFC 7519: JSON Web Token\nOWASP API Security Top 10".to_string(),
        },
        KnowledgeEntry {
            reference: "WSTG-APIT-01".to_string(),
            title: "gRPC Security Testing".to_string(),
            objective: "Identify security weaknesses in gRPC implementations including missing authentication, sensitive data exposure in protobuf messages, excessive message sizes, and service enumeration vulnerabilities.".to_string(),
            description: "gRPC is a high-performance RPC framework using Protocol Buffers and HTTP/2. Security testing gRPC services involves analyzing the protobuf message schemas for sensitive fields, verifying authentication controls, checking message size limits, and enumerating available services. gRPC's use of HTTP/2 also introduces unique considerations for proxy and interception testing.".to_string(),
            prerequisites: "Access to gRPC endpoints, .proto definition files or reflection API, understanding of Protocol Buffers wire format and HTTP/2 framing.".to_string(),
            testing_steps: "1. Enumerate available gRPC services using reflection API or proto imports.\n2. Analyze .proto definitions for sensitive fields.\n3. Capture gRPC traffic and inspect protobuf-encoded messages.\n4. Check if authentication is enforced on gRPC endpoints.\n5. Test for service reflection exposure.\n6. Verify message size limits are in place.\n7. Inspect gRPC metadata for credentials or tokens.\n8. Test service methods with various input payloads.".to_string(),
            expected_result: "gRPC services should:\n- Require authentication on all methods.\n- Not expose reflection API in production.\n- Limit message sizes (default 4MB).\n- Avoid sensitive data in protobuf fields.\n- Use TLS for all communication.\n- Implement rate limiting and input validation.".to_string(),
            required_evidence: ".proto files, captured gRPC frames, decoded protobuf messages, service enumeration results, authentication verification.".to_string(),
            references: "OWASP ASVS V4.1.1\nCWE-306: Missing Authentication\nCWE-359: Exposure of Private Information\ngRPC Security Documentation\nOWASP API Security Top 10 - API2:2023 Broken Authentication".to_string(),
        },
        KnowledgeEntry {
            reference: "WSTG-CLNT-10".to_string(),
            title: "WebSocket Security Testing".to_string(),
            objective: "Identify security weaknesses in WebSocket implementations including unencrypted connections, missing origin validation, unauthenticated access, and sensitive data exposure in frames.".to_string(),
            description: "WebSockets provide full-duplex communication channels over a single TCP connection. While they are powerful for real-time applications, they introduce unique security considerations. Testing includes verifying the WebSocket handshake, inspecting frame contents for sensitive data, validating origin checks, ensuring TLS encryption (wss://), and confirming that authentication is enforced before the upgrade is completed.".to_string(),
            prerequisites: "Access to WebSocket endpoints, ability to capture network traffic, understanding of RFC 6455 WebSocket protocol, browser developer tools or proxy.".to_string(),
            testing_steps: "1. Identify WebSocket endpoints in the application.\n2. Verify the upgrade handshake (HTTP 101 Switching Protocols).\n3. Check if wss:// is used everywhere (no ws:// in production).\n4. Validate the Origin header is checked by the server.\n5. Confirm authentication is enforced before handshake completion.\n6. Inspect WebSocket frames for sensitive data (tokens, PII, secrets).\n7. Test for cross-site WebSocket hijacking (CSWSH).\n8. Verify proper connection termination handling.\n9. Test message size limits and rate limiting.".to_string(),
            expected_result: "WebSocket implementations should:\n- Use wss:// exclusively in production.\n- Validate Origin headers against an allowlist.\n- Enforce authentication before completing the upgrade.\n- Not transmit sensitive data unencrypted.\n- Implement message size limits.\n- Properly handle connection errors and timeouts.\n- Use secure WebSocket subprotocols when applicable.".to_string(),
            required_evidence: "WebSocket handshake headers, captured frames, decoded frame payloads, origin validation test results, authentication bypass test results.".to_string(),
            references: "OWASP ASVS V4.1.1\nCWE-319: Cleartext Transmission\nCWE-346: Origin Validation Error\nRFC 6455: WebSocket Protocol\nOWASP HTML5 Security Cheat Sheet\nCWE-306: Missing Authentication".to_string(),
        },
    ]
}
